
package net.wyless.www;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PorthosWSF2Soap", targetNamespace = "https://www.wyless.net/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PorthosWSF2Soap {


    /**
     * 
     * @param value
     * @return
     *     returns java.lang.String
     */
    @WebMethod(action = "https://www.wyless.net/echoInt")
    @WebResult(name = "echoIntResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "echoInt", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.EchoInt")
    @ResponseWrapper(localName = "echoIntResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.EchoIntResponse")
    public String echoInt(
        @WebParam(name = "value", targetNamespace = "https://www.wyless.net/")
        int value);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.DeviceResponseType
     */
    @WebMethod(operationName = "SingleCDMAInquiry", action = "https://www.wyless.net/SingleCDMAInquiry")
    @WebResult(name = "SingleCDMAInquiryResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleCDMAInquiry", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleCDMAInquiry")
    @ResponseWrapper(localName = "SingleCDMAInquiryResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleCDMAInquiryResponse")
    public DeviceResponseType singleCDMAInquiry(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        DeviceInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleSIMInquiry", action = "https://www.wyless.net/SingleSIMInquiry")
    @WebResult(name = "SingleSIMInquiryResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleSIMInquiry", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSIMInquiry")
    @ResponseWrapper(localName = "SingleSIMInquiryResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSIMInquiryResponse")
    public ResponseType singleSIMInquiry(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleSuspendSIM", action = "https://www.wyless.net/SingleSuspendSIM")
    @WebResult(name = "SingleSuspendSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleSuspendSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSuspendSIM")
    @ResponseWrapper(localName = "SingleSuspendSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSuspendSIMResponse")
    public ResponseType singleSuspendSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        SuspendInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleRestoreSIM", action = "https://www.wyless.net/SingleRestoreSIM")
    @WebResult(name = "SingleRestoreSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleRestoreSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleRestoreSIM")
    @ResponseWrapper(localName = "SingleRestoreSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleRestoreSIMResponse")
    public ResponseType singleRestoreSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleActivateSIM", action = "https://www.wyless.net/SingleActivateSIM")
    @WebResult(name = "SingleActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleActivateSIM")
    @ResponseWrapper(localName = "SingleActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleActivateSIMResponse")
    public ResponseType singleActivateSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        ActivateInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.PlanResponseType
     */
    @WebMethod(operationName = "SingleChangePlan", action = "https://www.wyless.net/SingleChangePlan")
    @WebResult(name = "SingleChangePlanResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleChangePlan", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleChangePlan")
    @ResponseWrapper(localName = "SingleChangePlanResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleChangePlanResponse")
    public PlanResponseType singleChangePlan(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        PlanInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ChangeSIMResponseType
     */
    @WebMethod(operationName = "SingleChangeSIM", action = "https://www.wyless.net/SingleChangeSIM")
    @WebResult(name = "SingleChangeSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleChangeSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleChangeSIM")
    @ResponseWrapper(localName = "SingleChangeSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleChangeSIMResponse")
    public ChangeSIMResponseType singleChangeSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        ChangeSIMInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.QueryHLRResponseType
     */
    @WebMethod(operationName = "SingleQueryHLR", action = "https://www.wyless.net/SingleQueryHLR")
    @WebResult(name = "SingleQueryHLRResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleQueryHLR", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleQueryHLR")
    @ResponseWrapper(localName = "SingleQueryHLRResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleQueryHLRResponse")
    public QueryHLRResponseType singleQueryHLR(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleCancelDeviceLocation", action = "https://www.wyless.net/SingleCancelDeviceLocation")
    @WebResult(name = "SingleCancelDeviceLocationResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleCancelDeviceLocation", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleCancelDeviceLocation")
    @ResponseWrapper(localName = "SingleCancelDeviceLocationResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleCancelDeviceLocationResponse")
    public ResponseType singleCancelDeviceLocation(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleSendOTAMSISDN", action = "https://www.wyless.net/SingleSendOTAMSISDN")
    @WebResult(name = "SingleSendOTAMSISDNResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleSendOTAMSISDN", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSendOTAMSISDN")
    @ResponseWrapper(localName = "SingleSendOTAMSISDNResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSendOTAMSISDNResponse")
    public ResponseType singleSendOTAMSISDN(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleTopupMsisdn", action = "https://www.wyless.net/SingleTopupMsisdn")
    @WebResult(name = "SingleTopupMsisdnResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleTopupMsisdn", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleTopupMsisdn")
    @ResponseWrapper(localName = "SingleTopupMsisdnResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleTopupMsisdnResponse")
    public ResponseType singleTopupMsisdn(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        TopupInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleSendSMS", action = "https://www.wyless.net/SingleSendSMS")
    @WebResult(name = "SingleSendSMSResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleSendSMS", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSendSMS")
    @ResponseWrapper(localName = "SingleSendSMSResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleSendSMSResponse")
    public ResponseType singleSendSMS(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        SendSMSType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleDeActivateSIM", action = "https://www.wyless.net/SingleDeActivateSIM")
    @WebResult(name = "SingleDeActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleDeActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleDeActivateSIM")
    @ResponseWrapper(localName = "SingleDeActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleDeActivateSIMResponse")
    public ResponseType singleDeActivateSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "SingleReActivateSIM", action = "https://www.wyless.net/SingleReActivateSIM")
    @WebResult(name = "SingleReActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "SingleReActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleReActivateSIM")
    @ResponseWrapper(localName = "SingleReActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SingleReActivateSIMResponse")
    public ResponseType singleReActivateSIM(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        ReActivateInputType inputType);

    /**
     * 
     * @param bulkActInputType
     * @param callBackURL
     * @param transactionid
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkActivateSIM", action = "https://www.wyless.net/BulkActivateSIM")
    @WebResult(name = "BulkActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkActivateSIM")
    @ResponseWrapper(localName = "BulkActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkActivateSIMResponse")
    public BulkResponseType bulkActivateSIM(
        @WebParam(name = "bulkActInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkActivateInputType bulkActInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param bulkActCDMAInputType
     * @param callBackURL
     * @param transactionid
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkActivateCDMA", action = "https://www.wyless.net/BulkActivateCDMA")
    @WebResult(name = "BulkActivateCDMAResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkActivateCDMA", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkActivateCDMA")
    @ResponseWrapper(localName = "BulkActivateCDMAResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkActivateCDMAResponse")
    public BulkResponseType bulkActivateCDMA(
        @WebParam(name = "bulkActCDMAInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkActivateCDMAInputType bulkActCDMAInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkSuspInputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkSuspendCDMA", action = "https://www.wyless.net/BulkSuspendCDMA")
    @WebResult(name = "BulkSuspendCDMAResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkSuspendCDMA", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSuspendCDMA")
    @ResponseWrapper(localName = "BulkSuspendCDMAResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSuspendCDMAResponse")
    public BulkResponseType bulkSuspendCDMA(
        @WebParam(name = "bulkSuspInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkSuspendDeviceInputType bulkSuspInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkResInputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkRestoreCDMA", action = "https://www.wyless.net/BulkRestoreCDMA")
    @WebResult(name = "BulkRestoreCDMAResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkRestoreCDMA", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkRestoreCDMA")
    @ResponseWrapper(localName = "BulkRestoreCDMAResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkRestoreCDMAResponse")
    public BulkResponseType bulkRestoreCDMA(
        @WebParam(name = "bulkResInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkDeviceInputType bulkResInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkSuspInputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkSuspendSIM", action = "https://www.wyless.net/BulkSuspendSIM")
    @WebResult(name = "BulkSuspendSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkSuspendSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSuspendSIM")
    @ResponseWrapper(localName = "BulkSuspendSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSuspendSIMResponse")
    public BulkResponseType bulkSuspendSIM(
        @WebParam(name = "bulkSuspInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkSuspendInputType bulkSuspInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "CallBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param bulkInputType
     * @param transactionid
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkRestoreSIM", action = "https://www.wyless.net/BulkRestoreSIM")
    @WebResult(name = "BulkRestoreSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkRestoreSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkRestoreSIM")
    @ResponseWrapper(localName = "BulkRestoreSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkRestoreSIMResponse")
    public BulkResponseType bulkRestoreSIM(
        @WebParam(name = "bulkInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkInputType bulkInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkPlaninputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkChangePlan", action = "https://www.wyless.net/BulkChangePlan")
    @WebResult(name = "BulkChangePlanResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkChangePlan", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkChangePlan")
    @ResponseWrapper(localName = "BulkChangePlanResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkChangePlanResponse")
    public BulkResponseType bulkChangePlan(
        @WebParam(name = "bulkPlaninputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkPlanInputType bulkPlaninputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkchangeSIMInpType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkChangeSIM", action = "https://www.wyless.net/BulkChangeSIM")
    @WebResult(name = "BulkChangeSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkChangeSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkChangeSIM")
    @ResponseWrapper(localName = "BulkChangeSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkChangeSIMResponse")
    public BulkResponseType bulkChangeSIM(
        @WebParam(name = "bulkchangeSIMInpType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkChangeSIMInputType bulkchangeSIMInpType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param bulkInputType
     * @param transactionid
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkSendOTAMSISDN", action = "https://www.wyless.net/BulkSendOTAMSISDN")
    @WebResult(name = "BulkSendOTAMSISDNResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkSendOTAMSISDN", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSendOTAMSISDN")
    @ResponseWrapper(localName = "BulkSendOTAMSISDNResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkSendOTAMSISDNResponse")
    public BulkResponseType bulkSendOTAMSISDN(
        @WebParam(name = "bulkInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkInputType bulkInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "callBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkDeActivateInputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkDeActivateSIM", action = "https://www.wyless.net/BulkDeActivateSIM")
    @WebResult(name = "BulkDeActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkDeActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkDeActivateSIM")
    @ResponseWrapper(localName = "BulkDeActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkDeActivateSIMResponse")
    public BulkResponseType bulkDeActivateSIM(
        @WebParam(name = "bulkDeActivateInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkInputType bulkDeActivateInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "CallBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param callBackURL
     * @param transactionid
     * @param bulkReActivateInputType
     * @return
     *     returns net.wyless.www.BulkResponseType
     */
    @WebMethod(operationName = "BulkReActivateSIM", action = "https://www.wyless.net/BulkReActivateSIM")
    @WebResult(name = "BulkReActivateSIMResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "BulkReActivateSIM", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkReActivateSIM")
    @ResponseWrapper(localName = "BulkReActivateSIMResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.BulkReActivateSIMResponse")
    public BulkResponseType bulkReActivateSIM(
        @WebParam(name = "bulkReActivateInputType", targetNamespace = "https://www.wyless.net/")
        ArrayOfBulkReActivateInputType bulkReActivateInputType,
        @WebParam(name = "transactionid", targetNamespace = "https://www.wyless.net/")
        String transactionid,
        @WebParam(name = "CallBackURL", targetNamespace = "https://www.wyless.net/")
        String callBackURL);

    /**
     * 
     * @param accountNumber
     * @param transactionId
     * @param invoiceNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceSummary", action = "https://www.wyless.net/GetInvoiceSummary")
    @WebResult(name = "GetInvoiceSummaryResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "GetInvoiceSummary", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetInvoiceSummary")
    @ResponseWrapper(localName = "GetInvoiceSummaryResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetInvoiceSummaryResponse")
    public String getInvoiceSummary(
        @WebParam(name = "accountNumber", targetNamespace = "https://www.wyless.net/")
        String accountNumber,
        @WebParam(name = "invoiceNumber", targetNamespace = "https://www.wyless.net/")
        String invoiceNumber,
        @WebParam(name = "transactionId", targetNamespace = "https://www.wyless.net/")
        String transactionId);

    /**
     * 
     * @param accountNumber
     * @param transactionId
     * @param invoiceNumber
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "GetInvoiceDetail", action = "https://www.wyless.net/GetInvoiceDetail")
    @WebResult(name = "GetInvoiceDetailResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "GetInvoiceDetail", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetInvoiceDetail")
    @ResponseWrapper(localName = "GetInvoiceDetailResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetInvoiceDetailResponse")
    public String getInvoiceDetail(
        @WebParam(name = "accountNumber", targetNamespace = "https://www.wyless.net/")
        String accountNumber,
        @WebParam(name = "invoiceNumber", targetNamespace = "https://www.wyless.net/")
        String invoiceNumber,
        @WebParam(name = "transactionId", targetNamespace = "https://www.wyless.net/")
        String transactionId);

    /**
     * 
     * @param searchTable
     * @param transactionId
     * @param queryFilters
     * @return
     *     returns net.wyless.www.SearchResult
     */
    @WebMethod(operationName = "Search", action = "https://www.wyless.net/Search")
    @WebResult(name = "SearchResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "Search", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.Search")
    @ResponseWrapper(localName = "SearchResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.SearchResponse")
    public SearchResult search(
        @WebParam(name = "queryFilters", targetNamespace = "https://www.wyless.net/")
        String queryFilters,
        @WebParam(name = "searchTable", targetNamespace = "https://www.wyless.net/")
        SearchTableName searchTable,
        @WebParam(name = "transactionId", targetNamespace = "https://www.wyless.net/")
        String transactionId);

    /**
     * 
     * @param transactionId
     * @param msisdn
     * @return
     *     returns net.wyless.www.ConnectionStatus
     */
    @WebMethod(operationName = "GetNetworkConnectionOnlineStatus", action = "https://www.wyless.net/GetNetworkConnectionOnlineStatus")
    @WebResult(name = "GetNetworkConnectionOnlineStatusResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "GetNetworkConnectionOnlineStatus", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetNetworkConnectionOnlineStatus")
    @ResponseWrapper(localName = "GetNetworkConnectionOnlineStatusResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetNetworkConnectionOnlineStatusResponse")
    public ConnectionStatus getNetworkConnectionOnlineStatus(
        @WebParam(name = "msisdn", targetNamespace = "https://www.wyless.net/")
        String msisdn,
        @WebParam(name = "transactionId", targetNamespace = "https://www.wyless.net/")
        String transactionId);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "AssignIP", action = "https://www.wyless.net/AssignIP")
    @WebResult(name = "AssignIPResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "AssignIP", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AssignIP")
    @ResponseWrapper(localName = "AssignIPResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AssignIPResponse")
    public ResponseType assignIP(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        AssignIPInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ResponseType
     */
    @WebMethod(operationName = "ReleaseIP", action = "https://www.wyless.net/ReleaseIP")
    @WebResult(name = "ReleaseIPResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "ReleaseIP", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.ReleaseIP")
    @ResponseWrapper(localName = "ReleaseIPResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.ReleaseIPResponse")
    public ResponseType releaseIP(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        IPInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ProfileResponseType
     */
    @WebMethod(operationName = "AssignProfile", action = "https://www.wyless.net/AssignProfile")
    @WebResult(name = "AssignProfileResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "AssignProfile", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AssignProfile")
    @ResponseWrapper(localName = "AssignProfileResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AssignProfileResponse")
    public ProfileResponseType assignProfile(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        AssignProfileInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.ProfileResponseType
     */
    @WebMethod(operationName = "ReleaseProfile", action = "https://www.wyless.net/ReleaseProfile")
    @WebResult(name = "ReleaseProfileResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "ReleaseProfile", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.ReleaseProfile")
    @ResponseWrapper(localName = "ReleaseProfileResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.ReleaseProfileResponse")
    public ProfileResponseType releaseProfile(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        InputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "PING", action = "https://www.wyless.net/PING")
    @WebResult(name = "PINGResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "PING", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.PING")
    @ResponseWrapper(localName = "PINGResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.PINGResponse")
    public String ping(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        PingInputType inputType);

    /**
     * 
     * @param inputType
     * @return
     *     returns net.wyless.www.TagResponseType
     */
    @WebMethod(operationName = "AttachTags", action = "https://www.wyless.net/AttachTags")
    @WebResult(name = "AttachTagsResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "AttachTags", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AttachTags")
    @ResponseWrapper(localName = "AttachTagsResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AttachTagsResponse")
    public TagResponseType attachTags(
        @WebParam(name = "inputType", targetNamespace = "https://www.wyless.net/")
        TagInputType inputType);

    /**
     * 
     * @param objRequest
     * @return
     *     returns net.wyless.www.LocationResponseType
     */
    @WebMethod(operationName = "GetDeviceLocation", action = "https://www.wyless.net/GetDeviceLocation")
    @WebResult(name = "GetDeviceLocationResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "GetDeviceLocation", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetDeviceLocation")
    @ResponseWrapper(localName = "GetDeviceLocationResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.GetDeviceLocationResponse")
    public LocationResponseType getDeviceLocation(
        @WebParam(name = "objRequest", targetNamespace = "https://www.wyless.net/")
        LocationInputType objRequest);

    /**
     * 
     * @param objRequest
     * @return
     *     returns net.wyless.www.RegisterResponseType
     */
    @WebMethod(operationName = "RegisterDevice", action = "https://www.wyless.net/RegisterDevice")
    @WebResult(name = "RegisterDeviceResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "RegisterDevice", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.RegisterDevice")
    @ResponseWrapper(localName = "RegisterDeviceResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.RegisterDeviceResponse")
    public RegisterResponseType registerDevice(
        @WebParam(name = "objRequest", targetNamespace = "https://www.wyless.net/")
        RegisterInputType objRequest);

    /**
     * 
     * @param objRequest
     * @return
     *     returns net.wyless.www.RegisterResponseType
     */
    @WebMethod(operationName = "UnRegisterDevice", action = "https://www.wyless.net/UnRegisterDevice")
    @WebResult(name = "UnRegisterDeviceResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "UnRegisterDevice", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.UnRegisterDevice")
    @ResponseWrapper(localName = "UnRegisterDeviceResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.UnRegisterDeviceResponse")
    public RegisterResponseType unRegisterDevice(
        @WebParam(name = "objRequest", targetNamespace = "https://www.wyless.net/")
        RegisterInputType objRequest);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod(operationName = "Authenticate", action = "https://www.wyless.net/Authenticate")
    @WebResult(name = "AuthenticateResult", targetNamespace = "https://www.wyless.net/")
    @RequestWrapper(localName = "Authenticate", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.Authenticate")
    @ResponseWrapper(localName = "AuthenticateResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.AuthenticateResponse")
    public String authenticate();

    /**
     * 
     */
    @WebMethod(operationName = "Logout", action = "https://www.wyless.net/Logout")
    @RequestWrapper(localName = "Logout", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.Logout")
    @ResponseWrapper(localName = "LogoutResponse", targetNamespace = "https://www.wyless.net/", className = "net.wyless.www.LogoutResponse")
    public void logout();

}
