
package net.wyless.www;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * Porthos API v2.0
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PorthosWSF2", targetNamespace = "https://www.wyless.net/", wsdlLocation = "https://www.wyless.net:9443/PorthosAPI/PorthosWSF2.asmx?wsdl")
public class PorthosWSF2
    extends Service
{

    private final static URL PORTHOSWSF2_WSDL_LOCATION;
    private final static WebServiceException PORTHOSWSF2_EXCEPTION;
    private final static QName PORTHOSWSF2_QNAME = new QName("https://www.wyless.net/", "PorthosWSF2");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www.wyless.net:9443/PorthosAPI/PorthosWSF2.asmx?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        PORTHOSWSF2_WSDL_LOCATION = url;
        PORTHOSWSF2_EXCEPTION = e;
    }

    public PorthosWSF2() {
        super(__getWsdlLocation(), PORTHOSWSF2_QNAME);
    }

    public PorthosWSF2(WebServiceFeature... features) {
        super(__getWsdlLocation(), PORTHOSWSF2_QNAME, features);
    }

    public PorthosWSF2(URL wsdlLocation) {
        super(wsdlLocation, PORTHOSWSF2_QNAME);
    }

    public PorthosWSF2(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PORTHOSWSF2_QNAME, features);
    }

    public PorthosWSF2(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PorthosWSF2(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PorthosWSF2Soap
     */
    @WebEndpoint(name = "PorthosWSF2Soap")
    public PorthosWSF2Soap getPorthosWSF2Soap() {
        return super.getPort(new QName("https://www.wyless.net/", "PorthosWSF2Soap"), PorthosWSF2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PorthosWSF2Soap
     */
    @WebEndpoint(name = "PorthosWSF2Soap")
    public PorthosWSF2Soap getPorthosWSF2Soap(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.wyless.net/", "PorthosWSF2Soap"), PorthosWSF2Soap.class, features);
    }

    /**
     * 
     * @return
     *     returns PorthosWSF2Soap
     */
    @WebEndpoint(name = "PorthosWSF2Soap12")
    public PorthosWSF2Soap getPorthosWSF2Soap12() {
        return super.getPort(new QName("https://www.wyless.net/", "PorthosWSF2Soap12"), PorthosWSF2Soap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PorthosWSF2Soap
     */
    @WebEndpoint(name = "PorthosWSF2Soap12")
    public PorthosWSF2Soap getPorthosWSF2Soap12(WebServiceFeature... features) {
        return super.getPort(new QName("https://www.wyless.net/", "PorthosWSF2Soap12"), PorthosWSF2Soap.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PORTHOSWSF2_EXCEPTION!= null) {
            throw PORTHOSWSF2_EXCEPTION;
        }
        return PORTHOSWSF2_WSDL_LOCATION;
    }

}
